# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/young/OneDrive/Documents/- Hardware Labs/digital_systems-verilog/ecen340/Final_Project_Pong_Game/VGA_display/VGA_display.srcs/sources_1/ip/BITMAP_ROM/BITMAP_ROM.xci
# IP: The module: 'BITMAP_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/young/OneDrive/Documents/- Hardware Labs/digital_systems-verilog/ecen340/Final_Project_Pong_Game/VGA_display/VGA_display.gen/sources_1/ip/BITMAP_ROM/BITMAP_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BITMAP_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/young/OneDrive/Documents/- Hardware Labs/digital_systems-verilog/ecen340/Final_Project_Pong_Game/VGA_display/VGA_display.srcs/sources_1/ip/BITMAP_ROM/BITMAP_ROM.xci
# IP: The module: 'BITMAP_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/young/OneDrive/Documents/- Hardware Labs/digital_systems-verilog/ecen340/Final_Project_Pong_Game/VGA_display/VGA_display.gen/sources_1/ip/BITMAP_ROM/BITMAP_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BITMAP_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
